[build]
    command = "npm run build && npm run export"
    publish = "out"

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  UNIFORM_PROJECT_ID='Uniform Project Id'
  UNIFORM_API_KEY='Uniform API Key'
  GA4_ID='Google Analytics 4 ID (optional)'